# Generated by Django 4.1.4 on 2023-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('Date_of_Join', models.DateField()),
            ],
        ),
    ]
